settings:
  title: 'iOSMAN.us Network Status'
  url: 'https://status.iosman.us' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: i1-web-server # unique identifier
    name: i1-web-server
    description: 'i1 codenamed web server.' # default=empty
    url: 'http://ns3.iosman.us/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: osmandagdeviren-com-tr
    name: osmandagdeviren.com.tr
    url: 'https://osmandagdeviren.com.tr'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: iosman-us
    name: iosman.us
    url: 'https://iosman.us'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: akillim-net
    name: akillim.net
    url: 'https://akillim.net'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: akilliapartmanim-com
    name: akilliapartmanim.com
    url: 'https://akilliapartmanim.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
  - id: getir-us
    name: getir.us
    url: 'https://getir.us'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=
